// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using VirtualEvent.Model.Data.Configurations;
using VirtualEvent.Model.Models;

#nullable disable

namespace VirtualEvent.Model.Data
{
    public partial class VirtualEventsDbContext : DbContext
    {
        public VirtualEventsDbContext()
        {
        }

        public VirtualEventsDbContext(DbContextOptions<VirtualEventsDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AttendanceAttanchments> AttendanceAttanchments { get; set; }
        public virtual DbSet<Attendances> Attendances { get; set; }
        public virtual DbSet<EventAttachments> EventAttachments { get; set; }
        public virtual DbSet<Events> Events { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.AttendanceAttanchmentsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AttendancesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EventAttachmentsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EventsConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
