// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VirtualEvent.Model.Models
{
    public partial class Events
    {
        public Events()
        {
            Attendances = new HashSet<Attendances>();
            EventAttachments = new HashSet<EventAttachments>();
        }

        public int EventId { get; set; }
        public string OrganizerId { get; set; }
        public string Title { get; set; }
        public DateTime StartDate { get; set; }
        public TimeSpan StartTime { get; set; }
        public DateTime EndDate { get; set; }
        public TimeSpan EndTime { get; set; }
        public string Url { get; set; }
        public string Notes { get; set; }

        public virtual ICollection<Attendances> Attendances { get; set; }
        public virtual ICollection<EventAttachments> EventAttachments { get; set; }
    }
}