// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VirtualEvent.Model.Models
{
    public partial class EventAttachments
    {
        public int EventAttachmentId { get; set; }
        public int EventId { get; set; }
        public string Name { get; set; }

        public virtual Events Event { get; set; }
    }
}